package ru.espepe.bubuka.player.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ru.espepe.bubuka.player.dao.StorageFile;
import ru.espepe.bubuka.player.dao.Timelist;
import ru.espepe.bubuka.player.dao.Play;
import ru.espepe.bubuka.player.dao.Block;
import ru.espepe.bubuka.player.dao.Track;

import ru.espepe.bubuka.player.dao.StorageFileDao;
import ru.espepe.bubuka.player.dao.TimelistDao;
import ru.espepe.bubuka.player.dao.PlayDao;
import ru.espepe.bubuka.player.dao.BlockDao;
import ru.espepe.bubuka.player.dao.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storageFileDaoConfig;
    private final DaoConfig timelistDaoConfig;
    private final DaoConfig playDaoConfig;
    private final DaoConfig blockDaoConfig;
    private final DaoConfig trackDaoConfig;

    private final StorageFileDao storageFileDao;
    private final TimelistDao timelistDao;
    private final PlayDao playDao;
    private final BlockDao blockDao;
    private final TrackDao trackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storageFileDaoConfig = daoConfigMap.get(StorageFileDao.class).clone();
        storageFileDaoConfig.initIdentityScope(type);

        timelistDaoConfig = daoConfigMap.get(TimelistDao.class).clone();
        timelistDaoConfig.initIdentityScope(type);

        playDaoConfig = daoConfigMap.get(PlayDao.class).clone();
        playDaoConfig.initIdentityScope(type);

        blockDaoConfig = daoConfigMap.get(BlockDao.class).clone();
        blockDaoConfig.initIdentityScope(type);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        storageFileDao = new StorageFileDao(storageFileDaoConfig, this);
        timelistDao = new TimelistDao(timelistDaoConfig, this);
        playDao = new PlayDao(playDaoConfig, this);
        blockDao = new BlockDao(blockDaoConfig, this);
        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(StorageFile.class, storageFileDao);
        registerDao(Timelist.class, timelistDao);
        registerDao(Play.class, playDao);
        registerDao(Block.class, blockDao);
        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        storageFileDaoConfig.getIdentityScope().clear();
        timelistDaoConfig.getIdentityScope().clear();
        playDaoConfig.getIdentityScope().clear();
        blockDaoConfig.getIdentityScope().clear();
        trackDaoConfig.getIdentityScope().clear();
    }

    public StorageFileDao getStorageFileDao() {
        return storageFileDao;
    }

    public TimelistDao getTimelistDao() {
        return timelistDao;
    }

    public PlayDao getPlayDao() {
        return playDao;
    }

    public BlockDao getBlockDao() {
        return blockDao;
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
