package ru.espepe.bubuka.player.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ru.espepe.bubuka.player.dao.StorageFile;

import ru.espepe.bubuka.player.dao.StorageFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storageFileDaoConfig;

    private final StorageFileDao storageFileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storageFileDaoConfig = daoConfigMap.get(StorageFileDao.class).clone();
        storageFileDaoConfig.initIdentityScope(type);

        storageFileDao = new StorageFileDao(storageFileDaoConfig, this);

        registerDao(StorageFile.class, storageFileDao);
    }
    
    public void clear() {
        storageFileDaoConfig.getIdentityScope().clear();
    }

    public StorageFileDao getStorageFileDao() {
        return storageFileDao;
    }

}
